language: php

env:
  global:
    - APP_ENV=testing

# list any PHP version you want to test against
php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - composer update --prefer-source --no-interaction

script: vendor/bin/phpunit